language: ar

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 2
  max_ngram: 4
- name: RegexEntityExtractor
  case_sensitive: False
  use_lookup_tables: True
  use_regexes: True
- name: DIETClassifier
  epochs: 100
  constrain_similarities: true
  model_confidence: softmax

policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 50
  constrain_similarities: true
- name: RulePolicy
assistant_id: 20230619-123505-piercing-sap
